"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";

export default function WatchClient({ episodeId, title, nextId }: { episodeId: string; title: string; nextId: string | null }) {
  const router = useRouter(); const video = useRef<HTMLVideoElement>(null); const [locked, setLocked] = useState(false); const [coinPrice, setCoinPrice] = useState(0); const [muted, setMuted] = useState(true); const [liked, setLiked] = useState(false); const [watermark, setWatermark] = useState("");
  useEffect(() => { fetch(`/api/episodes/${episodeId}/playback`).then(async response => { if (response.ok) { const data = await response.json(); if (video.current) video.current.src = data.playbackUrl; setWatermark(data.watermark); } else if (response.status === 403) { const data = await response.json(); setLocked(true); setCoinPrice(data.coinPrice); } }); }, [episodeId]);
  const unlock = async (source: "coin" | "ad") => { const response = await fetch("/api/unlocks", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ episodeId, source }) }); if (response.ok) location.reload(); };
  return <div className="relative mx-auto aspect-[9/16] max-h-[calc(100vh-4rem)] max-w-[600px] overflow-hidden bg-zinc-900"><video ref={video} className="h-full w-full object-cover" controls playsInline muted={muted} onTimeUpdate={event => { if (Math.floor(event.currentTarget.currentTime) % 10 === 0) void fetch("/api/progress", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ episodeId, positionSec: Math.floor(event.currentTarget.currentTime) }) }); }} /><div className="pointer-events-none absolute right-3 top-1/2 -rotate-12 text-xs text-white/50">{watermark}</div><div className="absolute bottom-5 left-4 right-4 flex items-end justify-between"><div><p className="text-xs text-zinc-300">NOW PLAYING</p><h1 className="text-xl font-bold">{title}</h1></div><div className="flex gap-2"><button onClick={() => setMuted(value => !value)} className="rounded-full bg-black/60 px-3 py-2">{muted ? "🔇" : "🔊"}</button><button onClick={() => { setLiked(value => !value); void fetch("/api/likes", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ episodeId }) }); }} className="rounded-full bg-black/60 px-3 py-2">{liked ? "❤️" : "🤍"}</button>{nextId && <button onClick={() => router.push(`/watch/${nextId}`)} className="rounded-full bg-rose-500 px-3 py-2">Next ›</button>}</div></div>{locked && <div className="absolute inset-x-0 bottom-0 rounded-t-3xl bg-zinc-950 p-6"><p className="text-sm text-zinc-400">The cliffhanger continues.</p><h2 className="mt-1 text-2xl font-black">Unlock for 🪙 {coinPrice}</h2><div className="mt-5 flex gap-3"><button onClick={() => void unlock("coin")} className="rounded-full bg-rose-500 px-5 py-3 font-bold">Spend coins</button><button onClick={() => void unlock("ad")} className="rounded-full bg-zinc-800 px-5 py-3">Watch ad</button></div></div>}</div>;
}
